import { z } from 'zod';

/**
 * Zod Schema matching your Supabase 'product' table.
 * Includes auto-generated fields as optional to support both
 * Insert (new) and Select (existing) operations.
 */
export const productSchema = z.object({
  // Database Generated
  id: z.string().uuid().optional(),
  product_id: z.string().optional(), // format: sp00001
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),

  // Core Information
  name: z.string().min(1, 'Product name is required'),
  barcode: z.string().nullable().optional(), // Auto-generated by DB if empty

  // Pricing (Coerced for form compatibility)
  cost_price: z.coerce.number().min(0).default(0),
  wholesale_price: z.coerce.number().min(0).default(0),
  retail_price: z.coerce.number().min(0).default(0),

  // Inventory & Status
  stock_quantity: z.coerce.number().int().default(0), // Allows negative
  is_active: z.boolean().default(true),

  // Metadata
  manufacturer: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
});

/**
 * TypeScript Type inferred from the Zod Schema
 */
export type Product = z.infer<typeof productSchema>;

/**
 * Type for creating a new product (omitting DB-generated fields)
 */
export type CreateProductInput = z.input<typeof productSchema>;
